
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Intermediate Algebra'
tagline:          'from http://cnx.org/contents/02776133-d49d-49cb-bfaa-67c7f61b25a1@3.1 (CC-BY)'
url:              https://github.com/philschatz/algebra-intermediate-book
origin:           http://cnx.org/contents/02776133-d49d-49cb-bfaa-67c7f61b25a1@3.1

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          3.1

bookviewer:       http://philschatz.com/book-viewer

